### ISSUE TITLE
Possible switch from getenv() to $_ENV()

### ISSUE THREAD

**Issue by petrpacas** [oscarotero/env#3]
I'm currently using a shared webhost and as it turns out, they have `putenv()` (and consequently `getenv()`) disabled. And since your library is using `getenv()`, it doesn't work in that setup.

Since I might not be the only one to ever run into this issue, I wanted to ask whether your library could be updated to use `$_ENV[]` instead? I'm not very PHP-savvy, so, I might be asking the impossible here...

Thank you for your consideration.

(_Link to related issue I posted in [roots/bedrock](https://github.com/roots/bedrock/issues/323)._)

**Comment by oscarotero** [comment]
Interesting.
I've created a branch with a patch for this. Can you test it? If it works fine, I'll release the v1.1.0 tag

**Comment by petrpacas** [comment]
Unfortunately it doesn't seem to be helping.

**Comment by petrpacas** [comment]
Sorry for the first reply - I didn't notice the need for adding the `Env::USE_ENV_ARRAY` option.

```php
Env::init();
Env::$options = Env::USE_ENV_ARRAY;
```

After adding it it does work! Clever solution, Oscar 👏 

Edit just in case:
```php
Env::init();
Env::$options |= Env::USE_ENV_ARRAY;
```

**Comment by oscarotero** [comment]
Great.
Note that your configuration add only `USE_ENV_ARRAY`, but discard the default config. You should do this:

```php
Env::$options |= Env::USE_ENV_ARRAY;
```

**Comment by petrpacas** [comment]
I was kind of hoping you'll correct me if needed - thank you again.

Would you think it is better to include it before or after the `Env::init();`? I tested that it is arbitrary, but still...

**Comment by oscarotero** [comment]
ok, new version released. Enjoy :)
