### ISSUE TITLE
Add support for reading data from $_SERVER variable

### ISSUE THREAD

**Issue by ocean90** [oscarotero/env#8]
[PHP dotenv v5](https://github.com/vlucas/phpdotenv/releases/tag/v5.0.0) has switched to using the `$_SERVER` global as the default storage instead of the ~`putenv()`~ `$_ENV` variable (see [v4 fallback chain](https://github.com/vlucas/phpdotenv/blob/db63b2ea280fdcf13c4ca392121b0b2450b51193/src/Repository/RepositoryBuilder.php#L123-L128)). See [this comment](https://github.com/vlucas/phpdotenv/issues/446#issuecomment-639016097) by @GrahamCampbell for the reasoning behind this change.

What are you thoughts about adding a new `Env::USE_SERVER_ARRAY` option which reads the data from the `$_SERVER` variable?

Related: #3.

**Comment by GrahamCampbell** [comment]
> PHP dotenv v5 has switched to using the $_SERVER global as the default storage instead of putenv(). 

Not quite. We've been using `$_SERVER`, `$_ENV`, and `putenv` since v1. v5 drops `putenv` by default.

> option which reads the data from the $_SERVER variable?

Yep, this is where env variables actually are, and has always been the correct place to look.

**Comment by oscarotero** [comment]
@ocean90 I've added this option to env v2.1 (not released yet).

**Comment by ocean90** [comment]
Thanks! Was just going to submit a PR with the same changes. 😃

**Comment by GrahamCampbell** [comment]
Note that stripping quotes will certainly not be relevant for files loaded by phpdotenv. Quoted strings are processed without their quotes, already. Any quotes that appear would have been intentionally escaped by the user.

**Comment by oscarotero** [comment]
@GrahamCampbell I see, but this library is independent of how the variables are loaded. Some use phpdotenv, others another library or not library at all. Anyway, this is configurable.

**Comment by oscarotero** [comment]
New version released. Thanks guys!
